<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data
 */
function jir_mobile_resources_services_resources()
{
    $resources = array();

    /**
     * Include the necessary inc files
     */
    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_job_teaser.services');
//    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_job_full.services');
//    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_employer_teaser.services');
//    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_employer_full.services');

    /**
     * Service APIs for contents
     */
    watchdog('jirapi', 'Before call resource');
    $resources += job_teaser_resource();

    return $resources;
}