<?php
/**
* @file
* A description of what your module does.
*/

/**
 * Implements hook_init().
 */
function jir_mobile_resources_init()
{
    $method = $_SERVER['REQUEST_METHOD'];

    if (isset($_SERVER['HTTP_ORIGIN'])) {
        drupal_add_http_header('Access-Control-Allow-Origin', $_SERVER['HTTP_ORIGIN']);
    }
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
        drupal_add_http_header('Access-Control-Allow-Headers', $_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']);
    }
    if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'])) {
        drupal_add_http_header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    }
    if ($method == 'OPTIONS') {
        exit;
    }
}

/**
 * Implements hook_services_resources().
 * Create service resource for APIs to return the necessary json data
 */
function jir_mobile_resources_services_resources()
{
    $resources = array();

    /**
     * Include the necessary inc files
     */
    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_job_teaser.services');
//    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_job_full.services');
    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_employer_teaser.services');
//    module_load_include('inc', 'jir_mobile_resources', 'includes/jir_resources_employer_full.services');

    /**
     * Service APIs for contents
     */
    $resources += job_teaser_resource();
    $resources += employer_teaser_resource();

    return $resources;
}